### ISSUE TITLE
TBC Classic

### ISSUE THREAD

**Issue by tance77** [kemayo/wow-dropthecheapestthing#11]
Doesn't seem to function very well in TBC classic. More specifically with the addon Bagnon

**Comment by kemayo** [comment]
How so?

**Comment by kemayo** [comment]
Also, does the alpha help?

**Comment by tance77** [comment]
![image](https://user-images.githubusercontent.com/3421501/120576899-5ae15080-c3d8-11eb-9220-05be6f57d73c.png)
It starts doing this to bagnon.  It also seems to take a while to decide what is the cheapest item after dropping one item. Sorry there is no LUA error or I would drop it here.

Can you link the Alpha download?

**Comment by tance77** [comment]
I found the Alpha. This seems to be more stable.

**Comment by kemayo** [comment]
It's available here: https://www.curseforge.com/wow/addons/dropthecheapestthing/files/3335779

**Comment by kemayo** [comment]
Ah, just beat me to it. :D

**Comment by tance77** [comment]
Yup this seems to have fixed the issue.

**Comment by kemayo** [comment]
Excellent!
