### ISSUE TITLE
Request - "buy back" protection

### ISSUE THREAD

**Issue by Veyska** [kemayo/wow-dropthecheapestthing#26]
What it says on the label.  An option to limit junk selling to 12 items at a time so that if you realize oops you didn't want to sell that or "wait, how the heck did *that* end up flagged as junk?"¹ you can still snag it back before it gets buried and you have to resort to an item restoration charge.  :-)

(¹ Been there, done that albeit with a different since-broken mod, safely recovered the metaphorical t-shirt.)

**Comment by kemayo** [comment]
Seems like a sensible idea, I will take a look.
