### ISSUE TITLE
   attempt to index local 'ItemSlot' (a nil value)

### ISSUE THREAD

**Issue by yoshimo** [kemayo/wow-dropthecheapestthing#8]
Date: 2020-10-13 09:53:38
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\DropTheCheapestThing\bagnon.lua line 5:
   attempt to index local 'ItemSlot' (a nil value)

Probably Bagnon changed a little

**Comment by kemayo** [comment]
Yeah, looks like Bagnon has changed somehow. I'll take a look.
